#!/bin/bash

export HPP_HOST=192.168.56.1    
export ROS_IP=$HPP_HOST
export UR10_IP=`echo $HPP_HOST | sed 's/[0-9]\+$/1/'`
export ROS_MASTER_URI="http://$UR10_IP:11311"

#Solve the error on Gazebo: "Exception sending a message"
export IGN_IP=127.0.0.1

echo "HPP_HOST=$HPP_HOST"
echo "UR10_IP=$UR10_IP"
echo "ROS_MASTER_URI=$ROS_MASTER_URI"
