#!/bin/bash

export HPP_HOST=`ip -4 address 2>/dev/null|awk '/inet / {print $2}'|grep 10.68 | sed 's#/.*$##'`
export ROS_IP=$HPP_HOST
export TIAGO_IP=`echo $HPP_HOST | sed 's/[0-9]\+$/1/'`
export ROS_MASTER_URI="http://$TIAGO_IP:11311"

echo "HPP_HOST=$HPP_HOST"
echo "TIAGO_IP=$TIAGO_IP"
echo "ROS_MASTER_URI=$ROS_MASTER_URI"
